# Data layer for eps-ground-rapture: one S3 bucket holding the Parquet
# tables (under <data_prefix>/<table>/) and Athena query results
# (under athena-results/), a Glue database with one external table per
# Parquet directory, and an Athena workgroup wired to the results prefix.
#
# Table schemas come from var.tables (= deploy/terraform/tables.json,
# generated by the pipeline). Column names are pipeline-sanitized; the
# SerDe maps them to Parquet fields by ordinal position
# (parquet.column.index.access = true), because the raw Parquet names
# ("Us - Ud", "SS_uc+", ...) are not legal Athena identifiers.

locals {
  bucket_name    = "eps-ground-rapture-${var.env}"
  database_name  = "eps_ground_rapture_${var.env}"
  workgroup_name = "eps-ground-rapture-${var.env}"
  results_prefix = "athena-results/"
}

resource "aws_s3_bucket" "data" {
  bucket        = local.bucket_name
  force_destroy = var.force_destroy
}

resource "aws_s3_bucket_versioning" "data" {
  count  = var.versioning ? 1 : 0
  bucket = aws_s3_bucket.data.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "data" {
  bucket = aws_s3_bucket.data.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "data" {
  bucket = aws_s3_bucket.data.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_lifecycle_configuration" "data" {
  bucket = aws_s3_bucket.data.id

  rule {
    id     = "expire-athena-results"
    status = "Enabled"

    filter {
      prefix = local.results_prefix
    }

    expiration {
      days = var.results_expiration_days
    }

    # On a versioned bucket (prod) the expiration above only inserts a
    # delete marker; without this, every query result would live on
    # forever as a noncurrent version.
    noncurrent_version_expiration {
      noncurrent_days = 1
    }
  }

  # Clean up the delete markers the rule above leaves behind on the
  # versioned bucket. Must be a separate rule: expired_object_delete_marker
  # cannot be combined with `days` in one expiration block.
  rule {
    id     = "cleanup-athena-results-delete-markers"
    status = "Enabled"

    filter {
      prefix = local.results_prefix
    }

    expiration {
      expired_object_delete_marker = true
    }
  }

  rule {
    id     = "abort-incomplete-uploads"
    status = "Enabled"

    filter {}

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }
}

resource "aws_glue_catalog_database" "this" {
  name        = local.database_name
  description = "eps-ground-rapture ${var.env}: 2D DEM earthquake-rupture tables (Parquet on S3)."
}

resource "aws_glue_catalog_table" "table" {
  for_each = var.tables

  name          = each.key
  database_name = aws_glue_catalog_database.this.name
  table_type    = "EXTERNAL_TABLE"

  parameters = {
    EXTERNAL              = "TRUE"
    classification        = "parquet"
    "parquet.compression" = "SNAPPY"
  }

  storage_descriptor {
    location      = "s3://${aws_s3_bucket.data.bucket}/${var.data_prefix}/${each.key}/"
    input_format  = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"

    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"

      parameters = {
        "serialization.format"        = "1"
        "parquet.column.index.access" = "true"
      }
    }

    dynamic "columns" {
      for_each = each.value

      content {
        name    = columns.value.name
        type    = columns.value.type
        comment = columns.value.comment
      }
    }
  }
}

resource "aws_athena_workgroup" "this" {
  name          = local.workgroup_name
  description   = "eps-ground-rapture ${var.env} dashboards"
  state         = "ENABLED"
  force_destroy = var.force_destroy

  configuration {
    enforce_workgroup_configuration    = true
    publish_cloudwatch_metrics_enabled = false

    result_configuration {
      output_location = "s3://${aws_s3_bucket.data.bucket}/${local.results_prefix}"

      encryption_configuration {
        encryption_option = "SSE_S3"
      }
    }
  }
}
