variable "env" {
  description = "Deployment environment; selects bucket / database / workgroup names."
  type        = string

  validation {
    condition     = contains(["dev", "prod"], var.env)
    error_message = "env must be \"dev\" or \"prod\"."
  }
}

variable "tables" {
  description = <<-EOT
    Glue table schemas, keyed by table name. Generated by the data pipeline
    (`poetry run egr-build` writes deploy/terraform/tables.json) — do not
    hand-edit; the column ORDER is load-bearing because the Parquet SerDe
    maps columns by ordinal position.
  EOT
  type = map(list(object({
    name    = string
    type    = string
    comment = string
  })))
}

variable "force_destroy" {
  description = "Allow destroying the bucket (even with objects) and the Athena workgroup (even with named queries). Dev convenience; keep false in prod."
  type        = bool
  default     = false
}

variable "versioning" {
  description = "Enable S3 object versioning on the data bucket."
  type        = bool
  default     = false
}

variable "data_prefix" {
  description = "Key prefix under which the per-table Parquet directories live."
  type        = string
  default     = "processed"
}

variable "results_expiration_days" {
  description = "Days after which Athena query results under athena-results/ are expired."
  type        = number
  default     = 30
}
